### ISSUE TITLE
Fehlende Notizen zum zweiten Fahrzeug

### ISSUE THREAD

**Issue by EragonBromsohn** [Zenneo/leJOS_NXT_programs#1]
Bitte im notes Ordner eine txt Datei mit einer Beschreibung der Funktionalitäten des 2. NXTs hochladen.

Diesen Issue als gelöst melden, sobald erledigt

**Comment by chunkleader** [comment]
Wenn ich mich nicht täusche, machen wir den Roboter mit nur einem NXT, da nur noch ein Motor für den  Antrieb verwendet wird?
Dennoch müssen natürlich die Funktionalitäten der schwenkbaren Gabel geklärt werden.

**Comment by Zenneo** [comment]
Joa so wars gedacht. Der Arm muss doch in eine bestimmte Position kommen. Ich bin mir selber nicht so sicher, was für Operationen er durchführt. Vllt hast du ne bessere Vorstellung davon, was für Schritte ablaufen werden. Lass dich mal von der leJOS_NXT_programs/notes/group_project/software-description_vehicle.txt inspirieren und erstelle wenigstens die Datei. Schließ aber nicht dieses Issue

**Comment by Zenneo** [comment]
@EragonBromsohn bitte prüfe die Notes-Datei von @chunkleader und gebe eventuelle Verbesserungsvorschläge.

**Comment by Zenneo** [comment]
Notes wurde korrigiert und verbessert. @chunkleader bitte prüfe nach, ob wegen mir irgendwelche Fehler da sind oder noch etwas hinzugefügt werden kann.

**Comment by EragonBromsohn** [comment]
Der Roboterarm muss erkennen ob ein Box bei Station A bereit liegt. Dafür muss ein Sensor an der Gabel angebracht werden, sonst fährt der Roboter leere Runden.

**Comment by Zenneo** [comment]
Dafür bräuchten wir noch nen Ultraschallsensor für oder?

**Comment by EragonBromsohn** [comment]
Ja

 

Von: Zenneo [mailto:notifications@github.com] 
Gesendet: Sonntag, 17. Januar 2016 12:58
An: Zenneo/leJOS_NXT_programs
Cc: Eragon Bromson
Betreff: Re: [leJOS_NXT_programs] Fehlende Notizen zum zweiten Fahrzeug (#1)

 

Dafür bräuchten wir noch nen Ultraschallsensor für oder?

**Comment by Zenneo** [comment]
07946a8d5406751cca8ed42dcecc5c4727664d06 übernimmt die Änderungen. Falls diese Version ok ist, bitte hier bestätigen. @chunkleader kann den Issue schließen, sobald auch @EragonBromsohn damit einverstanden ist.

**Comment by Zenneo** [comment]
Notizen müssen eventuell überarbeitet werden. Fürs erste wird dieser Issue geschlossen.
